DROP DATABASE IF EXISTS pruebas1;
DROP ROLE IF EXISTS pruebas1;
CREATE ROLE pruebas1 WITH LOGIN ENCRYPTED PASSWORD 'pruebas1';
DROP ROLE IF EXISTS pruebas_admin;
CREATE ROLE pruebas_admin WITH LOGIN ENCRYPTED PASSWORD 'pruebas_admin';
DROP ROLE IF EXISTS pruebas_client;
CREATE ROLE pruebas_client WITH LOGIN ENCRYPTED PASSWORD 'pruebas_client';
DROP ROLE IF EXISTS pruebas_guest;
CREATE ROLE pruebas_guest WITH LOGIN ENCRYPTED PASSWORD 'pruebas_guest';
DROP DATABASE IF EXISTS pruebas1;
CREATE DATABASE pruebas1
 WITH
 OWNER = pruebas1
 ENCODING = 'UTF8'
 TABLESPACE = pg_default
 CONNECTION LIMIT = -1;
